# Generated by Django 5.2.15 on 2026-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableTimeSlots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date", "time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "time"), name="unique_available_time_slot"
                    )
                ],
            },
        ),
    ]
